/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_menu;

/**
 *
 * @author Aneta
 */
import java.util.List;
import java.util.Map;

//import pl.jsolve.sweetener.collection.Collections;
//import pl.jsolve.sweetener.collection.Maps;
//import templ4docx.util.Key;


import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
 
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;


import java.awt.*;
import javax.swing.*;
import javax.swing.JFrame;
import org.apache.poi.xwpf.usermodel.*;
import java.awt.Graphics.*;
import java.util.*;
import org.apache.xmlbeans.XmlCursor;
import java.io.File;

import org.apache.poi.xwpf.usermodel.XWPFDocument;



public class MainFrame_1 extends javax.swing.JFrame {
    MainMenu p2;
    /**
     * Creates new form MainFrame
     */
    public MainFrame_1() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int) tk.getScreenSize().getWidth();
        int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(ysize,xsize);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Next6 = new javax.swing.JLabel();
        Previous6 = new javax.swing.JLabel();
        Title7 = new javax.swing.JLabel();
        Exploring = new java.awt.TextArea();
        bg10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Next5 = new javax.swing.JLabel();
        Previous5 = new javax.swing.JLabel();
        Title5 = new javax.swing.JLabel();
        SeniorLevel = new java.awt.TextArea();
        bg9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Next4 = new javax.swing.JLabel();
        Previous4 = new javax.swing.JLabel();
        Title9 = new javax.swing.JLabel();
        EntryMidLevel = new java.awt.TextArea();
        bg8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Qualifications = new java.awt.TextArea();
        Next3 = new javax.swing.JLabel();
        Previous3 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        bg7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        OutgoingPersonality = new java.awt.TextArea();
        Next2 = new javax.swing.JLabel();
        Previous2 = new javax.swing.JLabel();
        Title8 = new javax.swing.JLabel();
        bg6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Next1 = new javax.swing.JLabel();
        Title6 = new javax.swing.JLabel();
        RecentGraduate = new java.awt.TextArea();
        bg5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Text2 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeButton.png"))); // NOI18N
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseButtonMouseExited(evt);
            }
        });
        jPanel1.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, -1));

        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimizeButton.png"))); // NOI18N
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseExited(evt);
            }
        });
        jPanel1.add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, -1, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/next.png"))); // NOI18N
        Next6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Next6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Next6MouseExited(evt);
            }
        });
        jPanel10.add(Next6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        Previous6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/previous.png"))); // NOI18N
        Previous6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Previous6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Previous6MouseExited(evt);
            }
        });
        jPanel10.add(Previous6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, -1, -1));

        Title7.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Title7.setForeground(new java.awt.Color(255, 255, 255));
        Title7.setText("EXPLORING CAREER OPPORTUNITIES");
        jPanel10.add(Title7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 720, -1));

        Exploring.setBackground(new java.awt.Color(153, 153, 153));
        Exploring.setEditable(false);
        Exploring.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel10.add(Exploring, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 710, 540));
        Exploring.append("\t January 1, 2014\n\n\n"
            + "\t Gloria Peter\n"
            + "\t 79950 Greene Terrace\n"
            + "\t Suite 98\n"
            + "\t Houston, RI 02886\n\n"
            + "\t Dear Ms. Peter:\n\n"
            + "\t Sincerely,\n\n"
            + "\t I am interested in exploring career opportunities in _______________ with \n"
            + "\t _______________ (company), and have therefore enclosed my resume for your \n"
            + "\t reference. Should you be in the market for a results-oriented professional for \n"
            + "\t your firm, I would encourage you to consider my credentials.\n\n"
            + "\t As my resume indicates, I have _______________ years experience in \n"
            + "\t _______________. My day-to-day output reflects a high level of motivation, \n"
            + "\t efficiency, and ability to meet any objective. I have a proven ability to \n"
            + "\t troubleshoot, perform under a minimum amount of supervision, and demonstrate \n"
            + "\t a high degree of initiative and good judgment.\n\n"
            + "\t I am interested in interviewing with you or one of your associates. I can be\n"
            + "\t reached at _______________ to arrange for an interview at a convenient time.\n\n"
            + "\t Drew Sterling\n\n"
            +"\t Enclosure\n"
        );

        bg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel10.add(bg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 730));
        jPanel10.setVisible(false);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/next.png"))); // NOI18N
        Next5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Next5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Next5MouseExited(evt);
            }
        });
        jPanel9.add(Next5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        Previous5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/previous.png"))); // NOI18N
        Previous5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Previous5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Previous5MouseExited(evt);
            }
        });
        jPanel9.add(Previous5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, -1, -1));

        Title5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Title5.setForeground(new java.awt.Color(255, 255, 255));
        Title5.setText("Senior Level");
        jPanel9.add(Title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 280, -1));

        SeniorLevel.setBackground(new java.awt.Color(153, 153, 153));
        SeniorLevel.setEditable(false);
        SeniorLevel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel9.add(SeniorLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 710, 540));
        SeniorLevel.append(
            "\t January 1, 2014\n\n\n"
            + "\t Clifford Harkins\n"
            + "\t 9773 Larkin Ave.\n"
            + "\t Suite 160\n"
            + "\t Glendale, AZ 85308\n\n"
            + "\t Dear Mr. Harkins:\n\n"
            + "\t Enclosed is my resume outlining more than _______________ years extensive \n"
            + "\t experience in _______________. As you will see, my credentials include \n"
            + "\t progressive responsibility with documented success in the areas of \n"
            + "\t _______________ at various organizational levels.\n\n"
            + "\t My impressive background will provide your department with a self-motivated, \n"
            + "\t helpful, and flexible associate who knows what is needed to get the job done. I\n"
            + "\t am both persuasive and capable of developing rapport and trust, as well as \n"
            + "\t experienced in influencing the attitudes and ideas of others.\n\n"
            + "\t Should you have an appropriate _______________ opening, I would welcome \n"
            + "\t the opportunity to meet with you personally to explore the contributions that I \n"
            + "\t could make to your corporation.\n"
            + "\t Sincerely,\n\n\n"
            + "\t Clifford Harkins\n\n"
            +"\t Enclosure\n"
        );

        bg9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel9.add(bg9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 730));
        jPanel9.setVisible(false);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/next.png"))); // NOI18N
        Next4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Next4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Next4MouseExited(evt);
            }
        });
        jPanel8.add(Next4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        Previous4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/previous.png"))); // NOI18N
        Previous4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Previous4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Previous4MouseExited(evt);
            }
        });
        jPanel8.add(Previous4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));

        Title9.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Title9.setForeground(new java.awt.Color(255, 255, 255));
        Title9.setText("Outgoing Personality");
        jPanel8.add(Title9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 410, -1));

        EntryMidLevel.setBackground(new java.awt.Color(153, 153, 153));
        EntryMidLevel.setEditable(false);
        EntryMidLevel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel8.add(EntryMidLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 710, 540));
        EntryMidLevel.append(
            "\t January 1, 2014\n\n\n"
            + "\t Sam Murphy\n"
            + "\t 845 Town and Country Common\n"
            + "\t Indianapolis, TX 78247\n\n"
            + "\t Dear Mr. Murphy:\n\n"
            + "\t Please consider my qualifications for the position of _______________. I have \n"
            + "\t learned that an opening is available on your team. I would seriously like to be \n"
            + "\t considered as a candidate.\n\n"
            + "\t With several years of experience in _______________, I am confident I will \n"
            + "\t make a significant contribution at your firm. What makes me different from other \n"
            + "\t applicants?\n"
            + "\t - I am self-motivated and dependable\n"
            + "\t - I have demonstrated poise and confidence while speaking and presenting\n"
            + "\t - I easily establish excellent rapport with others\n"
            + "\t - I can quickly identify needs and problems, and then provide solutions\n\n"
            + "\t If, after review of my resume, you would be interested in conducting an interview, \n"
            + "\t feel free to contact me at my home or office. I am very eager to meet with you and \n"
            + "\t explore the possibility of utilizing my experience and knowledge to benefit \n"
            + "\t _______________ (company). Thank you for your time and consideration.\n\n"
            + "\t Sincerely,\n\n\n"
            + "\t Drew Sterling\n\n"
            +"\t Enclosure\n"
        );

        bg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel8.add(bg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 790));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 730));
        jPanel8.setVisible(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Qualifications.setBackground(new java.awt.Color(153, 153, 153));
        Qualifications.setEditable(false);
        Qualifications.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel7.add(Qualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 710, 540));
        Qualifications.append(
            "\tJanuary 1, 2014\n\n\n"
            + "\tGlen Coleman\n"
            + "\t81559 Polaris Street\n"
            + "\tWorcester, MA 02375\n\n"
            + "\tDear Mr. Coleman:\n\n"
            + "\tAs a/an _______________, with experience in _______________, I feel my \n"
            + "\tbackground may be of interest to you. My qualifications include: \n"
            + "\t -  ___________________________\n"
            + "\t -  ___________________________\n"
            + "\t -  ___________________________\n\n"
            + "\tI have always had an interest in _______________, and believe that this \n"
            + "\tenthusiasm shows in my work. I respond well to a challenge and enjoy the \n"
            + "\topportunity to enjoy the rewards of hard work and dedication.\n\n"
            + "\tI look forward to hearing from you in the near future to schedule an interview at \n"
            + "\tyour convenience. I hope to learn more about your company's plans and goals, \n"
            + "\tand how I can contribute to its success.\n\n"
            + "\tSincerely,\n\n\n"
            + "\tDrew Sterling\n\n"
            + "\tEnclosure\n"
        );

        Next3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/next.png"))); // NOI18N
        Next3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Next3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Next3MouseExited(evt);
            }
        });
        jPanel7.add(Next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        Previous3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/previous.png"))); // NOI18N
        Previous3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Previous3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Previous3MouseExited(evt);
            }
        });
        jPanel7.add(Previous3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));

        Title3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("Qualifications");
        jPanel7.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 530, -1));

        bg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel7.add(bg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 730));
        jPanel7.setVisible(false);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OutgoingPersonality.setBackground(new java.awt.Color(153, 153, 153));
        OutgoingPersonality.setEditable(false);
        OutgoingPersonality.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel6.add(OutgoingPersonality, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 710, 540));
        OutgoingPersonality.append(
            "\tJanuary 1, 2014\n\n\n"
            + "\tEdward Adams\n"
            + "\t69008 Broadway Common\n"
            + "\tNew Castle, CA 91360-0396\n\n"
            + "\tDear Mr. Adams::\n\n"
            + "\tYesterday, as I was reviewing weekly job postings, I noticed your available \n"
            + "\t_______________ position. I am particularly interested in _______________ \n"
            + "\t(company) because it has both a great tradition and a great future in the \n"
            + "\t_______________ industry. It is obvious that your company is emerging as a \n"
            + "\tleader in the _______________ field. I would like to be on that team.\n\n"
            + "\tI believe that my organizational skills and my outgoing personality will enable me \n"
            + "\tto contribute to your high standards. I am confident I can provide many valuable \n"
            + "\tcontributions to your organization.\n\n"
            + "\tI look forward to hearing from you in the near future to schedule an interview at \n"
            + "\tyour convenience. I hope to learn more about your company's plans and goals, \n"
            + "\tand how I can contribute to its success.\n\n"
            + "\tSincerely,\n\n\n"
            + "\tDrew Sterling\n\n"
            + "\tEnclosure\n"
        );

        Next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/next.png"))); // NOI18N
        Next2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Next2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Next2MouseExited(evt);
            }
        });
        jPanel6.add(Next2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        Previous2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/previous.png"))); // NOI18N
        Previous2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Previous2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Previous2MouseExited(evt);
            }
        });
        jPanel6.add(Previous2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));

        Title8.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Title8.setForeground(new java.awt.Color(255, 255, 255));
        Title8.setText("Outgoing Personality");
        jPanel6.add(Title8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 410, -1));

        bg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel6.add(bg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 730));
        jPanel6.setVisible(false);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/next.png"))); // NOI18N
        Next1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Next1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Next1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Next1MouseExited(evt);
            }
        });
        jPanel5.add(Next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, -1, -1));

        Title6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Title6.setForeground(new java.awt.Color(255, 255, 255));
        Title6.setText("RECENT GRADUATE");
        jPanel5.add(Title6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 410, -1));

        RecentGraduate.setBackground(new java.awt.Color(153, 153, 153));
        RecentGraduate.setEditable(false);
        RecentGraduate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel5.add(RecentGraduate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 710, 540));
        RecentGraduate.append(
            "\tJanuary 1, 2014\n\n\n"
            + "\tMark Wilder\n"
            + "\t44773 Rock Willow Road\n"
            + "\tBallwin, MO 63011\n\n"
            + "\tDear Mr. Wilder:\n\n"
            + "\tBased on the criteria you listed, I believe I am an excellent candidate for the \n"
            + "\tposition of _______________.  Please accept the enclosed resume as my \n"
            + "\tapplication for the position.\n\n"
            + "\tAs a recent graduate, my professional job experience is necessarily limited.\n"
            + "\tHowever, I believe that you will find, and previous employers will verify, that I\n"
            + "\texhibit intelligence, common sense, initiative, maturity, and stability, and that I \n"
            + "\tam eager to make a positive contribution to your organization. \n\n"
            + "\tI am therefore respectfully requesting a personal interview. I feel confident that a \n"
            + "\tfrank, in-person discussion will determine if a compatible environment exists for \n"
            + "\ta future relationship. I would welcome this opportunity and assure you that this \n"
            + "\twould be time well spent. In advance, I thank you for your consideration and look\n"
            + "\tforward to meeting with you in the near future.\n\n"
            + "\tSincerely,\n\n\n"
            + "\tDrew Sterling\n\n"
            + "\tEnclosure\n"
        );

        bg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel5.add(bg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 730));
        jPanel5.setVisible(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/text2_1.png"))); // NOI18N
        jPanel4.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel4.add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 980, 480));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/text1.png"))); // NOI18N
        jPanel3.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 220));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel3.add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 980, 220));

        jPanel2.setBackground(java.awt.Color.darkGray);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoo.png"))); // NOI18N
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 100));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/b1.png"))); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B1MouseExited(evt);
            }
        });
        jPanel2.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/b2.png"))); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B2MouseExited(evt);
            }
        });
        jPanel2.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/b3.png"))); // NOI18N
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B3MouseExited(evt);
            }
        });
        jPanel2.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/b4.png"))); // NOI18N
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B4MouseExited(evt);
            }
        });
        jPanel2.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/b5.png"))); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B5MouseExited(evt);
            }
        });
        jPanel2.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainFrame1Buttons/b6.png"))); // NOI18N
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B6MouseExited(evt);
            }
        });
        jPanel2.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/back.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrameButtons/background.jpg"))); // NOI18N
        jPanel2.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1440, 790));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 730));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jPanel1.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initWorkScreen(){
        if(jPanel3.isDisplayable()){
            jPanel3.remove(Text1);
            jPanel3.remove(bg3);
        }
        if(jPanel4.isDisplayable()){
            jPanel4.remove(Text2);
            jPanel4.remove(bg4);
        }
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
    }
    private void B1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b1p.png"));
        B1.setIcon(I);
    }//GEN-LAST:event_B1MouseEntered

    private void B1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b1.png"));
        B1.setIcon(I);
    }//GEN-LAST:event_B1MouseExited

    private void B2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseEntered
         ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b2p.png"));
         B2.setIcon(I);
    }//GEN-LAST:event_B2MouseEntered

    private void B2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b2.png"));
        B2.setIcon(I);
    }//GEN-LAST:event_B2MouseExited

    private void B3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b3p.png"));
        B3.setIcon(I);
    }//GEN-LAST:event_B3MouseEntered

    private void B3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b3.png"));
        B3.setIcon(I);
    }//GEN-LAST:event_B3MouseExited

    private void B4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b4p.png"));
        B4.setIcon(I);
    }//GEN-LAST:event_B4MouseEntered

    private void B4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseExited
       ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b4.png"));
        B4.setIcon(I);
    }//GEN-LAST:event_B4MouseExited

    private void B5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b5p.png"));
        B5.setIcon(I);
    }//GEN-LAST:event_B5MouseEntered

    private void B5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b5.png"));
        B5.setIcon(I);
    }//GEN-LAST:event_B5MouseExited

    private void B6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b6p.png"));
        B6.setIcon(I);
    }//GEN-LAST:event_B6MouseEntered

    private void B6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/MainFrame1Buttons/b6.png"));
        B6.setIcon(I);
    }//GEN-LAST:event_B6MouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/backP.png"));
        back.setIcon(I);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/back.png"));
        back.setIcon(I);
    }//GEN-LAST:event_backMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        p2=new MainMenu();
        p2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
         initWorkScreen();
         jPanel5.setVisible(true);
         
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        initWorkScreen();
        jPanel6.setVisible(true);
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        initWorkScreen();
        jPanel7.setVisible(true);
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
       initWorkScreen();
       jPanel8.setVisible(true);
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        initWorkScreen();
        jPanel9.setVisible(true);
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        initWorkScreen();
        jPanel10.setVisible(true);
    }//GEN-LAST:event_B6MouseClicked

    private void CloseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/closeButtonP.png"));
        CloseButton.setIcon(I);
    }//GEN-LAST:event_CloseButtonMouseEntered

    private void CloseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/closeButton.png"));
        CloseButton.setIcon(I);
    }//GEN-LAST:event_CloseButtonMouseExited

    private void MinimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/minimizeButtonP.png"));
        MinimizeButton.setIcon(I);
    }//GEN-LAST:event_MinimizeButtonMouseEntered

    private void MinimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/minimizeButton.png"));
        MinimizeButton.setIcon(I);
    }//GEN-LAST:event_MinimizeButtonMouseExited

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
       setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void Next1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next1MouseClicked
        initWorkScreen();
        jPanel6.setVisible(true);
    }//GEN-LAST:event_Next1MouseClicked

    private void Next1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next1MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/nextP.png"));
        Next1.setIcon(I);
    }//GEN-LAST:event_Next1MouseEntered

    private void Next1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next1MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/next.png"));
        Next1.setIcon(I);
    }//GEN-LAST:event_Next1MouseExited

    private void Next2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next2MouseClicked
        initWorkScreen();
        jPanel7.setVisible(true);
    }//GEN-LAST:event_Next2MouseClicked

    private void Next2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next2MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/nextP.png"));
        Next2.setIcon(I);
    }//GEN-LAST:event_Next2MouseEntered

    private void Next2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next2MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/next.png"));
        Next2.setIcon(I);
    }//GEN-LAST:event_Next2MouseExited

    private void Previous2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous2MouseClicked
        initWorkScreen();
        jPanel5.setVisible(true);
    }//GEN-LAST:event_Previous2MouseClicked

    private void Previous2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous2MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previousP.png"));
        Previous2.setIcon(I);
    }//GEN-LAST:event_Previous2MouseEntered

    private void Previous2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous2MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previous.png"));
        Previous2.setIcon(I);
    }//GEN-LAST:event_Previous2MouseExited

    private void Next4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next4MouseClicked
        initWorkScreen();
        jPanel9.setVisible(true);
    }//GEN-LAST:event_Next4MouseClicked

    private void Next4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next4MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/nextP.png"));
        Next4.setIcon(I);
    }//GEN-LAST:event_Next4MouseEntered

    private void Next4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next4MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/next.png"));
        Next4.setIcon(I);
    }//GEN-LAST:event_Next4MouseExited

    private void Previous4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous4MouseClicked
        initWorkScreen();
        jPanel7.setVisible(true);
    }//GEN-LAST:event_Previous4MouseClicked

    private void Previous4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous4MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previousP.png"));
        Previous4.setIcon(I);
    }//GEN-LAST:event_Previous4MouseEntered

    private void Previous4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous4MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previous.png"));
        Previous4.setIcon(I);
    }//GEN-LAST:event_Previous4MouseExited

    private void Next5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next5MouseClicked
        initWorkScreen();
        jPanel10.setVisible(true);
    }//GEN-LAST:event_Next5MouseClicked

    private void Next5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next5MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/nextP.png"));
        Next5.setIcon(I);
    }//GEN-LAST:event_Next5MouseEntered

    private void Next5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next5MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/next.png"));
        Next5.setIcon(I);
    }//GEN-LAST:event_Next5MouseExited

    private void Previous5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous5MouseClicked
        initWorkScreen();
        jPanel8.setVisible(true);
    }//GEN-LAST:event_Previous5MouseClicked

    private void Previous5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous5MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previousP.png"));
        Previous5.setIcon(I);
    }//GEN-LAST:event_Previous5MouseEntered

    private void Previous5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous5MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previous.png"));
        Previous5.setIcon(I);
    }//GEN-LAST:event_Previous5MouseExited

    private void Next6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next6MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/nextP.png"));
        Next6.setIcon(I);
    }//GEN-LAST:event_Next6MouseEntered

    private void Next6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next6MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/next.png"));
        Next6.setIcon(I);
    }//GEN-LAST:event_Next6MouseExited

    private void Previous6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous6MouseClicked
        initWorkScreen();
        jPanel9.setVisible(true);
    }//GEN-LAST:event_Previous6MouseClicked

    private void Previous6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous6MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previousP.png"));
        Previous6.setIcon(I);
    }//GEN-LAST:event_Previous6MouseEntered

    private void Previous6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous6MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previous.png"));
        Previous6.setIcon(I);
    }//GEN-LAST:event_Previous6MouseExited

    private void Previous3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous3MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previous.png"));
        Previous3.setIcon(I);
    }//GEN-LAST:event_Previous3MouseExited

    private void Previous3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous3MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/previousP.png"));
        Previous3.setIcon(I);
    }//GEN-LAST:event_Previous3MouseEntered

    private void Previous3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous3MouseClicked
        initWorkScreen();
        jPanel6.setVisible(true);
    }//GEN-LAST:event_Previous3MouseClicked

    private void Next3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next3MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/next.png"));
        Next3.setIcon(I);
    }//GEN-LAST:event_Next3MouseExited

    private void Next3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next3MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/FrameButtons/nextP.png"));
        Next3.setIcon(I);
    }//GEN-LAST:event_Next3MouseEntered

    private void Next3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next3MouseClicked
        initWorkScreen();
        jPanel8.setVisible(true);
    }//GEN-LAST:event_Next3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel CloseButton;
    private java.awt.TextArea EntryMidLevel;
    private java.awt.TextArea Exploring;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JLabel Next1;
    private javax.swing.JLabel Next2;
    private javax.swing.JLabel Next3;
    private javax.swing.JLabel Next4;
    private javax.swing.JLabel Next5;
    private javax.swing.JLabel Next6;
    private java.awt.TextArea OutgoingPersonality;
    private javax.swing.JLabel Previous2;
    private javax.swing.JLabel Previous3;
    private javax.swing.JLabel Previous4;
    private javax.swing.JLabel Previous5;
    private javax.swing.JLabel Previous6;
    private java.awt.TextArea Qualifications;
    private java.awt.TextArea RecentGraduate;
    private java.awt.TextArea SeniorLevel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel Title6;
    private javax.swing.JLabel Title7;
    private javax.swing.JLabel Title8;
    private javax.swing.JLabel Title9;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel bg10;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg5;
    private javax.swing.JLabel bg6;
    private javax.swing.JLabel bg7;
    private javax.swing.JLabel bg8;
    private javax.swing.JLabel bg9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
    
}
