/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main_menu;
import java.awt.*;
import javax.swing.*;
import javax.swing.JFrame;
/**
 *
 * @author Aneta
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    MainFrame p1;
    MainFrame_1 p2;
    MainFrame_2 p3;
    MainFrame4 p5;
    public MainMenu() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int) tk.getScreenSize().getWidth();
        int ysize= (int) tk.getScreenSize().getHeight();
        this.setSize(ysize,xsize);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        screen = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeButton.png"))); // NOI18N
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseButtonMouseExited(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, -1));

        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimizeButton.png"))); // NOI18N
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseExited(evt);
            }
        });
        getContentPane().add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, -1, -1));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1.png"))); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B1MouseExited(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2.png"))); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B2MouseExited(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b3.png"))); // NOI18N
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B3MouseExited(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b4.png"))); // NOI18N
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B4MouseExited(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b5.png"))); // NOI18N
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B6MouseExited(evt);
            }
        });
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b6.png"))); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B5MouseExited(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/screen.png"))); // NOI18N
        screen.setPreferredSize(new java.awt.Dimension(400, 435));
        getContentPane().add(screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 760, 530));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg3.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b1p.png"));
        B1.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen1.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B1MouseEntered

    private void B1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b1.png"));
        B1.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B1MouseExited

    private void B2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b2p.png"));
        B2.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen2.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B2MouseEntered

    private void B2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b2.png"));
        B2.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B2MouseExited

    private void B3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b3p.png"));
        B3.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen3.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B3MouseEntered

    private void B3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b3.png"));
        B3.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B3MouseExited

    private void B4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b4p.png"));
        B4.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen4.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B4MouseEntered

    private void B4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b4.png"));
        B4.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B4MouseExited

    private void B6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b5p.png"));
        B6.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen6.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B6MouseEntered

    private void B6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b5.png"));
        B6.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B6MouseExited

    private void B5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b6p.png"));
        B5.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen5.png"));
        screen.setIcon(II);
        
    }//GEN-LAST:event_B5MouseEntered

    private void B5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/b6.png"));
        B5.setIcon(I);
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/screen.png"));
        screen.setIcon(II);
    }//GEN-LAST:event_B5MouseExited

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        p1=new MainFrame();
        p1.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_B1MouseClicked

    private void CloseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/closeButtonP.png"));
        CloseButton.setIcon(I);
    }//GEN-LAST:event_CloseButtonMouseEntered

    private void CloseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/closeButton.png"));
        CloseButton.setIcon(I);
    }//GEN-LAST:event_CloseButtonMouseExited

    private void MinimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseEntered
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/minimizeButtonP.png"));
        MinimizeButton.setIcon(I);
    }//GEN-LAST:event_MinimizeButtonMouseEntered

    private void MinimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseExited
        ImageIcon I = new ImageIcon(getClass().getResource("/Images/minimizeButton.png"));
        MinimizeButton.setIcon(I);
    }//GEN-LAST:event_MinimizeButtonMouseExited

    private void CloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        p2=new MainFrame_1();
        p2.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        p3=new MainFrame_2();
        p3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B3MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        p5=new MainFrame4();
        p5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    Thread.sleep(4500);
                }
                catch(Exception e){
                    
                }
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel CloseButton;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel screen;
    // End of variables declaration//GEN-END:variables
}
